[Decoder]
hw_accele_enable=0

[Storage]
path=./output

[Color]
enable=0
width=1080
height=1920
fps=60
format=MJPG

[Depth]
enable=0
width=960
height=1280
fps=30

[IR]
enable=false

[RawPhase]
[Property]
sync=true
watch=false

[Config]
AutoConnect=true
SaveFirmwareLog=true
NetDeviceIP=192.168.1.10
NetDevicePort=8090
RefreshRate=30
MaxDepthDistance=12000
IsDeviceClockSyncFirstConnected=true
savePngWithExposureGain=false

; -- OrbbecViewer language. If no config option, UI language is followed system language.
;english=true
isTriggerRenderMode=false

; Whether to show low-FPS warnings in trigger mode (software/hardware)
allowLowFpsWarningInTrigger=false

; access mode for GigE network device
; MR: Monitor read, read-only; no write or control privileges
; EA: Exclusive access, full read/write, no other application allowed; can preempt existing monitor access
; CA: Control access: read/write allowed; other applications permitted read-only monitor access
; Default: default access mode; control access for capable devices, ignored otherwise
accessMode=Default

[Curl]
geturl=https://vcp.developer.orbbec.com.cn/experience_api/v1/algorithm/list
posturl=https://vcp.developer.orbbec.com.cn/experience_api/
getFirmwareListUrl=http://159.27.233.135:8080/api/firmware/queryAll
FirmwareUrl=http://app.orbbec.com:8080/
[OBViewerLog]
WriteToFile=true
FileDir=./Log/OBViewer/
MaxFileSize=2048000000000
MaxFiles=10
